# Generated by Django 5.2 on 2025-06-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportgallery',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
