# Generated by Django 5.2 on 2025-04-14 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports_base', '0002_event_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='datime',
            new_name='date',
        ),
    ]
