# Generated by Django 5.2 on 2025-07-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_base', '0002_alter_sportgallery_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='coaches/'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='designation',
            field=models.CharField(choices=[('head_coach', 'Head Coach'), ('coach', 'Coach'), ('assistant_coach', 'Assistant Coach')], default='coach', max_length=100),
        ),
    ]
