# Generated by Django 5.2 on 2025-07-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_base', '0003_coach_photo_alter_coach_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='sport',
        ),
        migrations.AddField(
            model_name='coach',
            name='sports',
            field=models.ManyToManyField(related_name='coaches', to='sports_base.sport'),
        ),
    ]
