# Generated by Django 5.2 on 2025-07-09 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sports_Users', '0007_certificate'),
        ('sports_base', '0004_remove_coach_sport_coach_sports'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Match',
            new_name='MatchResult',
        ),
    ]
