# Generated by Django 5.2 on 2025-04-17 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports_base', '0007_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
