# Generated by Django 5.2 on 2025-04-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_base', '0010_sportschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='sports_gallery/')),
            ],
        ),
    ]
