# Generated by Django 5.2 on 2025-04-23 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports_base', '0012_coach_player_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='team',
            name='players',
        ),
        migrations.DeleteModel(
            name='Coach',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
