# Generated by Django 5.2 on 2025-04-27 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_base', '0013_remove_team_coach_remove_team_players_delete_coach_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=200)),
                ('team1_name', models.CharField(max_length=100)),
                ('team1_score', models.CharField(max_length=50)),
                ('team1_status', models.CharField(choices=[('WIN', 'Win'), ('LOSS', 'Loss'), ('DRAW', 'Draw')], max_length=10)),
                ('team2_name', models.CharField(max_length=100)),
                ('team2_score', models.CharField(max_length=50)),
                ('team2_status', models.CharField(choices=[('WIN', 'Win'), ('LOSS', 'Loss'), ('DRAW', 'Draw')], max_length=10)),
                ('match_result', models.CharField(max_length=100)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports_base.sport')),
            ],
        ),
    ]
