# Generated by Django 5.2 on 2025-04-27 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports_base', '0014_match'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Match',
        ),
    ]
