# Generated by Django 5.2 on 2025-04-27 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports_base', '0016_team_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='sport',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
