# Generated by Django 5.2 on 2025-06-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HODMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Professor Dr. Tahir', max_length=100)),
                ('message', models.TextField(default='Keeping in view the challenges posed to man by emerging trends of the present millennium, we have introduced a system of education that is based on the lines and parameters of modern approaches in the field of science and education.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hod_photos/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomePic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousel/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
