# Generated by Django 5.2 on 2025-07-08 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0002_hodmessage_homepic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
