# Generated by Django 5.2 on 2025-04-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0002_coach_player_sport_match_team_matchresult_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchresult',
            name='match',
        ),
        migrations.RemoveField(
            model_name='matchresult',
            name='winner',
        ),
        migrations.AlterField(
            model_name='team',
            name='sport',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='MatchResult',
        ),
        migrations.DeleteModel(
            name='Sport',
        ),
    ]
