# Generated by Django 5.2 on 2025-04-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0003_remove_matchresult_match_remove_matchresult_winner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sports', models.CharField(choices=[('football', 'Football'), ('basketball', 'Basketball'), ('cricket', 'Cricket'), ('tennis', 'Tennis'), ('volleyball', 'Volleyball')], max_length=20)),
                ('team_1', models.CharField(max_length=100)),
                ('team_2', models.CharField(max_length=100)),
                ('score_team_1', models.IntegerField()),
                ('score_team_2', models.IntegerField()),
                ('result', models.CharField(choices=[('win', 'Win'), ('loss', 'Loss'), ('draw', 'Draw')], max_length=10)),
                ('match_date', models.DateField()),
                ('venue', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-match_date'],
            },
        ),
    ]
