# Generated by Django 5.2 on 2025-04-28 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0004_match'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Match',
        ),
    ]
