# Generated by Django 5.2 on 2025-06-15 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Sports_Users', '0001_initial'),
        ('sports_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='sport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sports_base.sport'),
        ),
    ]
