# Generated by Django 5.2 on 2025-06-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sports_Users', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='is_captain',
        ),
        migrations.RemoveField(
            model_name='player',
            name='number',
        ),
        migrations.AlterField(
            model_name='player',
            name='college_roll_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='disability',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
