# Generated by Django 5.2 on 2025-06-15 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sports_Users', '0003_remove_player_is_captain_remove_player_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='position',
        ),
    ]
