# Generated by Django 5.2 on 2025-06-26 06:55

import Sports_Users.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sports_Users', '0006_customuser_status_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('certificate_file', models.FileField(upload_to='certificates/', validators=[Sports_Users.models.restrict_file_to_pdf])),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='Sports_Users.player')),
            ],
        ),
    ]
