# Generated by Django 5.2 on 2025-08-15 23:01

import Sports_Users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sports_Users', '0007_certificate'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', Sports_Users.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
